export const mockCandidateList = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    skills: "Java, Python, SQL",
    experience: "3 years",
    resumeUrl: "https://example.com/johndoe_resume.pdf",
    jobsAppliedTo: "Software Engineer, Data Analyst",
  },
  {
    id: 2,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    skills: "UX/UI Design, Sketch, Adobe XD",
    experience: "2 years",
    resumeUrl: "https://example.com/alicejohnson_resume.pdf",
    jobsAppliedTo: "UX Designer, Graphic Designer",
  },
  {
    id: 3,
    name: "Michael Smith",
    email: "michael.smith@example.com",
    skills: "Digital Marketing, SEO, Social Media",
    experience: "4 years",
    resumeUrl: "https://example.com/michaelsmith_resume.pdf",
    jobsAppliedTo: "Marketing Specialist, Social Media Manager",
  },
  {
    id: 4,
    name: "Emily White",
    email: "emily.white@example.com",
    skills: "Network Security, Cisco Routing, TCP/IP",
    experience: "5 years",
    resumeUrl: "https://example.com/emilywhite_resume.pdf",
    jobsAppliedTo: "Network Administrator, IT Security Analyst",
  },
  {
    id: 5,
    name: "Daniel Evans",
    email: "daniel.evans@example.com",
    skills: "Project Management, Leadership, Communication",
    experience: "6 years",
    resumeUrl: "https://example.com/danielevans_resume.pdf",
    jobsAppliedTo: "Project Manager, Supply Chain Manager",
  },
  {
    id: 6,
    name: "Jessica Brown",
    email: "jessica.brown@example.com",
    skills: "HR Policies, Employee Relations, Recruitment",
    experience: "3 years",
    resumeUrl: "https://example.com/jessicabrown_resume.pdf",
    jobsAppliedTo: "Human Resources Specialist, Legal Counsel",
  },
  {
    id: 7,
    name: "Ryan Miller",
    email: "ryan.miller@example.com",
    skills: "Sales, Negotiation, Relationship Building",
    experience: "4 years",
    resumeUrl: "https://example.com/ryanmiller_resume.pdf",
    jobsAppliedTo: "Sales Representative, Biomedical Scientist",
  },
  {
    id: 8,
    name: "Olivia Turner",
    email: "olivia.turner@example.com",
    skills: "Social Media Marketing, Content Creation, Analytics",
    experience: "2 years",
    resumeUrl: "https://example.com/oliviaturner_resume.pdf",
    jobsAppliedTo: "Social Media Manager, Electrical Engineer",
  },
  {
    id: 9,
    name: "Ethan White",
    email: "ethan.white@example.com",
    skills: "Content Creation, Editing, SEO",
    experience: "1 year",
    resumeUrl: "https://example.com/ethanwhite_resume.pdf",
    jobsAppliedTo: "Content Writer, QA Tester",
  },
  {
    id: 10,
    name: "Isabella Turner",
    email: "isabella.turner@example.com",
    skills: "Inventory Management, Logistics, Procurement",
    experience: "4 years",
    resumeUrl: "https://example.com/isabellaturner_resume.pdf",
    jobsAppliedTo: "Supply Chain Manager, Healthcare Administrator",
  },
];
