// export const mockJobList = [
//   { id: 1, title: "Software Engineer" },
//   { id: 2, title: "Product Manager" },
// ];

import Utils from "@utils/index";

export const mockJobList = [
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Software Engineer",
    description: "Develop and maintain software applications.",
    company: "TechCo",
    location: "San Francisco, CA",
    postedDate: "2024-02-19T12:00:00Z",
    requirements:
      "Bachelor's degree in Computer Science, 3+ years of experience",
    skills: "Java, Python, JavaScript",
    salaryRange: "70,000 - 100,000 USD",
    candidates: "John Doe, Jane Smith",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Data Analyst",
    description: "Analyze and interpret complex data sets.",
    company: "DataTech",
    location: "New York, NY",
    postedDate: "2024-02-18T10:30:00Z",
    requirements: "Master's degree in Statistics, Strong analytical skills",
    skills: "SQL, Excel, Statistical Analysis",
    salaryRange: "60,000 - 80,000 USD",
    candidates: "Alice Johnson, Bob Williams",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "UX Designer",
    description: "Create user-friendly and visually appealing interfaces.",
    company: "DesignSolutions",
    location: "Los Angeles, CA",
    postedDate: "2024-02-17T15:45:00Z",
    requirements: "Bachelor's degree in Design, Proficiency in design tools",
    skills: "Adobe XD, Sketch, UI/UX principles",
    salaryRange: "65,000 - 90,000 USD",
    candidates: "Emily Brown, David Lee",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Marketing Specialist",
    description: "Develop and implement marketing strategies.",
    company: "MarketingMasters",
    location: "Chicago, IL",
    postedDate: "2024-02-16T14:20:00Z",
    requirements: "Bachelor's degree in Marketing, 2+ years of experience",
    skills: "Social Media, SEO, Content Creation",
    salaryRange: "50,000 - 70,000 USD",
    candidates: "Megan Anderson, Michael Taylor",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Network Administrator",
    description: "Manage and maintain computer networks.",
    company: "NetworkPro",
    location: "Dallas, TX",
    postedDate: "2024-02-15T13:10:00Z",
    requirements: "Bachelor's degree in IT, Cisco certification",
    skills: "TCP/IP, Cisco Routing, Network Security",
    salaryRange: "75,000 - 110,000 USD",
    candidates: "Ryan Miller, Olivia White",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Financial Analyst",
    description: "Analyze financial data and provide insights.",
    company: "FinanceExperts",
    location: "Seattle, WA",
    postedDate: "2024-02-14T11:55:00Z",
    requirements: "Bachelor's degree in Finance, 3+ years of experience",
    skills: "Excel, Financial Modeling, Data Analysis",
    salaryRange: "70,000 - 90,000 USD",
    candidates: "Peter Adams, Susan Martinez",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Customer Support Representative",
    description: "Assist customers with product inquiries and issues.",
    company: "CustomerCare",
    location: "Miami, FL",
    postedDate: "2024-02-13T10:40:00Z",
    requirements: "High school diploma, Excellent communication skills",
    skills: "Customer Service, Problem Solving, Communication",
    salaryRange: "40,000 - 55,000 USD",
    candidates: "Chris Johnson, Sarah Davis",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Graphic Designer",
    description: "Create visual concepts for various projects.",
    company: "CreativeDesigns",
    location: "Denver, CO",
    postedDate: "2024-02-12T09:25:00Z",
    requirements:
      "Bachelor's degree in Graphic Design, Proficiency in design software",
    skills: "Photoshop, Illustrator, Creativity",
    salaryRange: "55,000 - 75,000 USD",
    candidates: "Alex Turner, Rachel Smith",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Project Manager",
    description: "Coordinate and oversee project activities.",
    company: "ProjectLeaders",
    location: "Houston, TX",
    postedDate: "2024-02-11T08:15:00Z",
    requirements:
      "Bachelor's degree, PMP certification, 5+ years of project management experience",
    skills: "Project Management, Leadership, Communication",
    salaryRange: "80,000 - 120,000 USD",
    candidates: "Daniel Evans, Jessica Brown",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Human Resources Specialist",
    description: "Manage HR processes and employee relations.",
    company: "HRPro",
    location: "Atlanta, GA",
    postedDate: "2024-02-10T07:00:00Z",
    requirements: "Bachelor's degree in HR, 2+ years of HR experience",
    skills: "Employee Relations, Recruitment, HR Policies",
    salaryRange: "50,000 - 70,000 USD",
    candidates: "Mark Johnson, Laura Taylor",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Sales Representative",
    description: "Promote and sell products or services.",
    company: "SalesPro",
    location: "Phoenix, AZ",
    postedDate: "2024-02-09T06:45:00Z",
    requirements: "Bachelor's degree, Proven sales experience",
    skills: "Sales, Negotiation, Relationship Building",
    salaryRange: "60,000 - 80,000 USD",
    candidates: "Kevin Miller, Olivia Turner",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "IT Security Analyst",
    description: "Protect computer systems and networks from cyber threats.",
    company: "SecurityTech",
    location: "Austin, TX",
    postedDate: "2024-02-08T05:30:00Z",
    requirements:
      "Bachelor's degree in IT, Certified Information Systems Security Professional (CISSP)",
    skills: "Cybersecurity, Network Security, Risk Assessment",
    salaryRange: "75,000 - 100,000 USD",
    candidates: "Lucas Evans, Amanda White",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Content Writer",
    description: "Create engaging and informative content.",
    company: "ContentCreators",
    location: "Portland, OR",
    postedDate: "2024-02-07T04:15:00Z",
    requirements:
      "Bachelor's degree in English or related field, Writing experience",
    skills: "Content Creation, Editing, SEO",
    salaryRange: "45,000 - 60,000 USD",
    candidates: "Ethan Brown, Hannah Taylor",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Quality Assurance Tester",
    description: "Test and ensure the quality of software products.",
    company: "QAExperts",
    location: "Las Vegas, NV",
    postedDate: "2024-02-06T03:00:00Z",
    requirements: "Bachelor's degree in IT, QA Certification",
    skills: "Manual Testing, Automated Testing, Bug Tracking",
    salaryRange: "55,000 - 75,000 USD",
    candidates: "Nathan Johnson, Lily Smith",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Healthcare Administrator",
    description: "Manage and coordinate healthcare facility operations.",
    company: "HealthcarePro",
    location: "Orlando, FL",
    postedDate: "2024-02-05T02:45:00Z",
    requirements:
      "Bachelor's degree in Healthcare Administration, 3+ years of healthcare management",
    skills: "Healthcare Operations, Leadership, Communication",
    salaryRange: "70,000 - 90,000 USD",
    candidates: "Grace Turner, Benjamin Davis",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Social Media Manager",
    description: "Create and implement social media strategies.",
    company: "SocialMediaMasters",
    location: "San Diego, CA",
    postedDate: "2024-02-04T01:30:00Z",
    requirements:
      "Bachelor's degree in Marketing, Social Media Management experience",
    skills: "Social Media Marketing, Content Creation, Analytics",
    salaryRange: "60,000 - 80,000 USD",
    candidates: "Sophia Miller, Ethan White",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Electrical Engineer",
    description: "Design and develop electrical systems.",
    company: "ElectroTech",
    location: "Raleigh, NC",
    postedDate: "2024-02-03T00:15:00Z",
    requirements:
      "Bachelor's degree in Electrical Engineering, 2+ years of experience",
    skills: "Circuit Design, Power Systems, Electronics",
    salaryRange: "75,000 - 100,000 USD",
    candidates: "Logan Johnson, Emma Brown",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Legal Counsel",
    description: "Provide legal advice and support.",
    company: "LegalExperts",
    location: "Nashville, TN",
    postedDate: "2024-02-02T23:00:00Z",
    requirements:
      "Juris Doctor (JD), Bar admission, 5+ years of legal experience",
    skills: "Legal Research, Contract Negotiation, Litigation",
    salaryRange: "90,000 - 120,000 USD",
    candidates: "Olivia Davis, Matthew Turner",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Biomedical Scientist",
    description: "Conduct research in the field of biomedical science.",
    company: "BioResearch",
    location: "Minneapolis, MN",
    postedDate: "2024-02-01T22:45:00Z",
    requirements: "Ph.D. in Biomedical Science, Research experience",
    skills: "Laboratory Techniques, Data Analysis, Research Ethics",
    salaryRange: "80,000 - 110,000 USD",
    candidates: "Henry Evans, Victoria Smith",
    JobDetail: [],
  },
  {
    id: Utils.helpers.generateRandomId(8),
    title: "Supply Chain Manager",
    description: "Optimize and manage the supply chain process.",
    company: "SupplyChainPros",
    location: "Detroit, MI",
    postedDate: "2024-01-31T21:30:00Z",
    requirements:
      "Bachelor's degree in Supply Chain Management, 4+ years of supply chain experience",
    skills: "Inventory Management, Logistics, Procurement",
    salaryRange: "80,000 - 100,000 USD",
    candidates: "Michael Johnson, Isabella Turner",
    JobDetail: [],
  },
];
