export enum ButtonTitle {
  OK = "OK",
  OKAY = "Okay",
  BACK = "Back",
  CANCEL = "Cancel",
  CONFIRM = "Confirm",
  LOGIN = "Login",
  FORGOT_PASSWORD = "Forgot password?",
  LOGIN_FACEBOOK = "Login with Facebook",
  LOGIN_GOOGLE = "Login with Google",
  SIGN_UP = "Sign-up",
  RESEND = "Resend",
  SUBMIT = "Submit",
  ADD = "ADD",
  EDIT = "Edit",
  HOME = "Home",
  LOGOUT = "Logout",
  VERIFY = "Verify",
}
