export enum ButtonTitle {
  OK = 'OK',
  OKAY = 'Okay',
  BACK = 'Back',
  CANCEL = 'Cancel',
  CONFIRM = 'Confirm',
  LOGIN = 'Login',
  FORGOT_PASSWORD = 'Forgot password?',
  LOGIN_FACEBOOK = 'Login with Facebook',
  LOGIN_GOOGLE = 'Login with Google',
  SIGN_UP = 'Sign-up',
  RESEND = 'Resend',
  SUBMIT = 'Submit',
  DELIVER_TO = 'Deliver to',
  ADD = 'ADD',
  LOOK_MAP = 'Look up the map',
  EDIT = 'Edit',
  HOME = 'Home',
  OFFICE = 'Office',
  LOCATE_ME = 'Locate Me',
  PROVIDE_LOCATION = 'Provide Delivery Location',
  CONFIRM_LOCATION = 'Confirm Location',
}
